export const dynamic = "force-dynamic";

import { ModalProvider } from '@/components/providers/modal-provider';
import { QueryProvider } from '@/components/providers/query-provider';
import { SocketProvider } from '@/components/providers/socket-provider';
import { ThemeProvider } from '@/components/providers/theme-provider';
import { cn } from '@/lib/utils';
import { ClerkProvider } from '@clerk/nextjs';
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';
import { extractRouterConfig } from "uploadthing/server";
import './globals.css';


import { ourFileRouter } from "@/app/api/uploadthing/core";


const font = Open_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'DevFix',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={cn(font.className,"bg-white dark:bg-[#313338]")}>
          <ThemeProvider attribute="class" defaultTheme='dark' enableSystem={false} storageKey='discord-theme'>
          <SocketProvider>
          <ModalProvider />
          <QueryProvider>
          <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
            {children}
          </QueryProvider>
          </SocketProvider>
          </ThemeProvider>
        </body>  
      </html>
    </ClerkProvider>
  )
}
